# Generated by Django 4.2 on 2023-10-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW ', 'Withdraw')], default=0, max_length=9)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
